name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:
      branches:
        - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: sudo apt install libclang1-18 && sudo apt install libclang-cpp18 && npm ci && npm run get-doxygen && npm run sdkgen && hugo -b https://bakkesmodwiki.github.io/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
